apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: ta-liberty-pipeline-docker-secret
  namespace: ta-liberty-pipeline-pro
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
  labels:
    serviceAccount: ta-liberty-pipeline-service-account
data:
  password: MTI3NDRmZDk
  username: Z2FuZGhpY2xvdWQ=